---
- name: Reiniciar el Servicio Nginx
  hosts: all
  become: true

  tasks:
    - name: "Validar: Verificar el estado actual de Nginx"
      ansible.builtin.shell: systemctl is-active nginx
      register: nginx_before
      ignore_errors: true

    - name: "Monitoreo: Mostrar estado antes del reinicio"
      ansible.builtin.debug:
        msg: "Estado antes: {{ nginx_before.stdout }}"

    - name: "Ejecución: Reiniciar el servicio Nginx"
      ansible.builtin.shell: systemctl restart nginx

    - name: "Validar: Verificar el estado de Nginx después del reinicio"
      ansible.builtin.shell: systemctl is-active nginx
      register: nginx_after

    - name: "Monitoreo: Mostrar estado después del reinicio"
      ansible.builtin.debug:
        msg: "Estado después: {{ nginx_after.stdout }}"

    - name: "Estado: Estado del servicio"
      ansible.builtin.set_fact:
        estado: "{{ (nginx_after.stdout == 'active') | ternary('success', 'failed') }}"

    - name: "Respuesta: Respuesta para ServiceNow" 
      ansible.builtin.uri:
        url: "https://dev267740.service-now.com/api/2067471/awx_remediation/result"
        method: POST
        user: admin
        password: IgVB=7/Y4dxd
        force_basic_auth: yes
        body_format: json
        body:
          alert_sys_id: "{{ SN_ALERT_SYS_ID }}"
          incident_sys_id: "{{ SN_INCIDENT_SYS_ID }}"
          status: "{{ estado }}"
        validate_certs: false